version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - cache:/app/.cache
    ports:
      - '25800:25800'
    command: ["npm", "run", "develop", "--", "--host", "0.0.0.0", "--port", "25800"]

volumes:
  node_modules:
  cache:
